{
 "title": "Marisight Seismic Monitor",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Global Seismic Activity Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    lat AS latitude,\r\n    lon AS longitude,\r\n    mag AS magnitude,\r\n    flynn_region AS title\r\nFROM marisight_db.seismic_events\r\nWHERE lat IS NOT NULL AND lon IS NOT NULL"
    },
    {
     "rawSql": "SELECT\r\n    lat AS latitude,\r\n    lon AS longitude,\r\n    mag AS magnitude,\r\n    flynn_region AS title\r\nFROM marisight_db.seismic_events\r\nWHERE lat IS NOT NULL \r\nAND lon IS NOT NULL\r\nAND mag >= 5.5"
    }
   ]
  },
  {
   "title": "Magnitude over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    parseDateTimeBestEffort(event_time) AS time,\r\n    mag AS magnitude\r\nFROM marisight_db.seismic_events \r\nWHERE event_time IS NOT NULL\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Seismic Intensity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    multiIf(mag < 2, 'Minor (<2)',\r\n            mag < 4, 'Light (2-4)',\r\n            mag < 6, 'Moderate (4-6)',\r\n            'Strong (6+)') AS category,\r\n    count() AS count\r\nFROM marisight_db.seismic_events\r\nWHERE mag IS NOT NULL\r\nGROUP BY category"
    }
   ]
  },
  {
   "title": "Earthquakes per Day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toDate(parseDateTimeBestEffort(event_time)) AS day, \r\n    count() AS earthquakes\r\nFROM marisight_db.seismic_events\r\nWHERE event_time IS NOT NULL\r\nGROUP BY day\r\nORDER BY day ASC"
    }
   ]
  },
  {
   "title": "Top 10 Strongest Earthquakes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    parseDateTimeBestEffort(event_time) AS time,\r\n    flynn_region AS location,\r\n    mag AS magnitude,\r\n    depth\r\nFROM marisight_db.seismic_events\r\nORDER BY magnitude DESC\r\nLIMIT 10"
    }
   ]
  }
 ]
}