marisight_dbt:
  outputs:
    dev:
      type: snowflake
      account: "OWYTLDT-HL95604" # مثلاً xy12345.us-east-1
      user: "Amira"
      password: "Applejack12345"
      role: SYSADMIN  # أو الـ Role اللي الدكتور قايلكم تشتغلوا بيه
      database: PROJECT_DB # اسم الداتا بيس بتاعتكم جوه سنوفليك
      warehouse: COMPUTE_WH # اسم الـ Warehouse اللي شغالين بيه
      schema: DBO
      threads: 4
  target: dev