CREATE DATABASE IF NOT EXISTS PROJECT_DB;
USE DATABASE PROJECT_DB;
CREATE SCHEMA IF NOT EXISTS dbo;
USE SCHEMA DBO;

CREATE OR REPLACE STAGE s3_stage
  URL = 's3://marisight-staging-layer-121913093195-us-east-1-an/ports/'
  CREDENTIALS = (
    AWS_KEY_ID = 'YOUR_AWS_KEY_ID_HERE'
    AWS_SECRET_KEY = 'YOUR_AWS_SECRET_KEY_HERE'
  );
list @s3_stage

CREATE OR REPLACE TABLE PROJECT_DB.DBO.PORTS (
    OID_                                        FLOAT,
    World_Port_Index_Number                     FLOAT,
    Region_Name                                 STRING,
    Main_Port_Name                              STRING,
    Alternate_Port_Name                         STRING,
    UN_LOCODE                                   STRING,
    Country_Code                                STRING,
    World_Water_Body                            STRING,
    IHO_S_130_Sea_Area                          STRING,
    Sailing_Direction_or_Publication            STRING,
    Publication_Link                            STRING,
    Standard_Nautical_Chart                     STRING,
    IHO_S_57_Electronic_Navigational_Chart      STRING,
    IHO_S_101_Electronic_Navigational_Chart     STRING,
    Digital_Nautical_Chart                      STRING,
    Tidal_Range_m                               FLOAT,
    Entrance_Width_m                            FLOAT,
    Channel_Depth_m                             FLOAT,
    Anchorage_Depth_m                           FLOAT,
    Cargo_Pier_Depth_m                          FLOAT,
    Oil_Terminal_Depth_m                        FLOAT,
    Liquified_Natural_Gas_Terminal_Depth_m      FLOAT,
    Maximum_Vessel_Length_m                     FLOAT,
    Maximum_Vessel_Beam_m                       FLOAT,
    Maximum_Vessel_Draft_m                      FLOAT,
    Offshore_Maximum_Vessel_Length_m            FLOAT,
    Offshore_Maximum_Vessel_Beam_m              FLOAT,
    Offshore_Maximum_Vessel_Draft_m             FLOAT,
    Harbor_Size                                 STRING,
    Harbor_Type                                 STRING,
    Harbor_Use                                  STRING,
    Shelter_Afforded                            STRING,
    Entrance_Restriction_Tide                   STRING,
    Entrance_Restriction_Heavy_Swell            STRING,
    Entrance_Restriction_Ice                    STRING,
    Entrance_Restriction_Other                  STRING,
    Overhead_Limits                             STRING,
    Underkeel_Clearance_Management_System       STRING,
    Good_Holding_Ground                         STRING,
    Turning_Area                                STRING,
    Port_Security                               STRING,
    Estimated_Time_of_Arrival_Message           STRING,
    Quarantine_Pratique                         STRING,
    Quarantine_Sanitation                       STRING,
    Quarantine_Other                            STRING,
    Traffic_Separation_Scheme                   STRING,
    Vessel_Traffic_Service                      STRING,
    First_Port_of_Entry                         STRING,
    US_Representative                           STRING,
    Pilotage_Compulsory                         STRING,
    Pilotage_Available                          STRING,
    Pilotage_Local_Assistance                   STRING,
    Pilotage_Advisable                          STRING,
    Tugs_Salvage                                STRING,
    Tugs_Assistance                             STRING,
    Communications_Telephone                    STRING,
    Communications_Telefax                      STRING,
    Communications_Radio                        STRING,
    Communications_Radiotelephone               STRING,
    Communications_Airport                      STRING,
    Communications_Rail                         STRING,
    Search_and_Rescue                           STRING,
    NAVAREA                                     STRING,
    Facilities_Wharves                          STRING,
    Facilities_Anchorage                        STRING,
    Facilities_Dangerous_Cargo_Anchorage        STRING,
    Facilities_Med_Mooring                      STRING,
    Facilities_Beach_Mooring                    STRING,
    Facilities_Ice_Mooring                      STRING,
    Facilities_Ro_Ro                            STRING,
    Facilities_Solid_Bulk                       STRING,
    Facilities_Liquid_Bulk                      STRING,
    Facilities_Container                        STRING,
    Facilities_Breakbulk                        STRING,
    Facilities_Oil_Terminal                     STRING,
    Facilities_LNG_Terminal                     STRING,
    Facilities_Other                            STRING,
    Medical_Facilities                          STRING,
    Garbage_Disposal                            STRING,
    Chemical_Holding_Tank_Disposal              STRING,
    Degaussing                                  STRING,
    Dirty_Ballast_Disposal                      STRING,
    Cranes_Fixed                                STRING,
    Cranes_Mobile                               STRING,
    Cranes_Floating                             STRING,
    Cranes_Container                            STRING,
    Lifts_100_Plus_Tons                         STRING,
    Lifts_50_100_Tons                           STRING,
    Lifts_25_49_Tons                            STRING,
    Lifts_0_24_Tons                             STRING,
    Services_Longshoremen                       STRING,
    Services_Electricity                        STRING,
    Services_Steam                              STRING,
    Services_Navigation_Equipment               STRING,
    Services_Electrical_Repair                  STRING,
    Services_Ice_Breaking                       STRING,
    Services_Diving                             STRING,
    Supplies_Provisions                         STRING,
    Supplies_Potable_Water                      STRING,
    Supplies_Fuel_Oil                           STRING,
    Supplies_Diesel_Oil                         STRING,
    Supplies_Aviation_Fuel                      STRING,
    Supplies_Deck                               STRING,
    Supplies_Engine                             STRING,
    Repairs                                     STRING,
    Dry_Dock                                    STRING,
    Railway                                     STRING,
    Latitude                                    FLOAT,
    Longitude                                   FLOAT
);

select * from project_db.dbo.ports

SELECT COUNT(*) FROM ports;


