{{ config(
    materialized='table'
) }}

SELECT
    WORLD_PORT_INDEX_NUMBER,
    MAIN_PORT_NAME,
    ALTERNATE_PORT_NAME,
    COUNTRY_CODE,
    REGION_NAME,
    UN_LOCODE,
    WORLD_WATER_BODY,
    LATITUDE,
    LONGITUDE,
    IS_VALID_COORDINATES,
    HARBOR_SIZE,
    HARBOR_TYPE,
    HARBOR_USE,
    SHELTER_AFFORDED,
    CHANNEL_DEPTH_M,
    ANCHORAGE_DEPTH_M,
    CARGO_PIER_DEPTH_M,
    OIL_TERMINAL_DEPTH_M,
    MAXIMUM_VESSEL_LENGTH_M,
    MAXIMUM_VESSEL_BEAM_M,
    MAXIMUM_VESSEL_DRAFT_M,
    ENTRANCE_RESTRICTION_TIDE,
    ENTRANCE_RESTRICTION_HEAVY_SWELL,
    ENTRANCE_RESTRICTION_ICE,
    ENTRANCE_RESTRICTION_OTHER,
    PORT_SECURITY,
    FIRST_PORT_OF_ENTRY,
    REPAIRS,
    DRY_DOCK,
    COMMUNICATIONS_TELEPHONE,
    COMMUNICATIONS_RADIO,
    COMMUNICATIONS_AIRPORT,
    COMMUNICATIONS_TELEFAX,     -- رجعناه تانى لأنه منور في السيلفر عندك
    SUPPLIES_PROVISIONS,
    SUPPLIES_POTABLE_WATER,
    SUPPLIES_FUEL_OIL,
    SUPPLIES_DIESEL_OIL,
    FACILITIES_CONTAINER,
    FACILITIES_RO_RO,
    FACILITIES_LIQUID_BULK,
    FACILITIES_SOLID_BULK,
    FACILITIES_OIL_TERMINAL,
    CRANES_CONTAINER,          -- العمود الصح الوحيد المتاح في السيلفر

    -- ── Derived: Supply Score (0–5) بناءً على الـ 5 عوامل ───────────────────
    (
        CASE WHEN UPPER(SUPPLIES_PROVISIONS)    IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
        CASE WHEN UPPER(SUPPLIES_POTABLE_WATER) IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
        CASE WHEN UPPER(SUPPLIES_FUEL_OIL)      IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
        CASE WHEN UPPER(SUPPLIES_DIESEL_OIL)    IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
        CASE WHEN UPPER(REPAIRS)                IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END
    ) AS SUPPLY_SCORE,

    CASE
        WHEN (
            CASE WHEN UPPER(SUPPLIES_PROVISIONS)    IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(SUPPLIES_POTABLE_WATER) IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(SUPPLIES_FUEL_OIL)      IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(SUPPLIES_DIESEL_OIL)    IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(REPAIRS)                IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END
        ) = 5 THEN 'Excellent'
        WHEN (
            CASE WHEN UPPER(SUPPLIES_PROVISIONS)    IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(SUPPLIES_POTABLE_WATER) IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(SUPPLIES_FUEL_OIL)      IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(SUPPLIES_DIESEL_OIL)    IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(REPAIRS)                IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END
        ) >= 3 THEN 'Good'
        WHEN (
            CASE WHEN UPPER(SUPPLIES_PROVISIONS)    IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(SUPPLIES_POTABLE_WATER) IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(SUPPLIES_FUEL_OIL)      IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(SUPPLIES_DIESEL_OIL)    IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END +
            CASE WHEN UPPER(REPAIRS)                IN ('YES','LIMITED','MODERATE','MAJOR') THEN 1 ELSE 0 END
        ) >= 1 THEN 'Limited'
        ELSE 'Unavailable'
    END AS SUPPLY_RATING,

    -- ── Derived: Communication Score (0–4) متقفل على الـ 4 عوامل بتوع المستند ──
    (
        CASE WHEN UPPER(COMMUNICATIONS_RADIO)     = 'YES' THEN 1 ELSE 0 END +
        CASE WHEN UPPER(COMMUNICATIONS_TELEPHONE) = 'YES' THEN 1 ELSE 0 END +
        CASE WHEN UPPER(COMMUNICATIONS_AIRPORT)   = 'YES' THEN 1 ELSE 0 END +
        CASE WHEN UPPER(COMMUNICATIONS_TELEFAX)   = 'YES' THEN 1 ELSE 0 END 
    ) AS COMMUNICATION_SCORE,

    CASE
        WHEN (
            CASE WHEN UPPER(COMMUNICATIONS_RADIO)     = 'YES' THEN 1 ELSE 0 END +
            CASE WHEN UPPER(COMMUNICATIONS_TELEPHONE) = 'YES' THEN 1 ELSE 0 END +
            CASE WHEN UPPER(COMMUNICATIONS_AIRPORT)   = 'YES' THEN 1 ELSE 0 END +
            CASE WHEN UPPER(COMMUNICATIONS_TELEFAX)   = 'YES' THEN 1 ELSE 0 END
        ) = 4 THEN 'Excellent'
        WHEN (
            CASE WHEN UPPER(COMMUNICATIONS_RADIO)     = 'YES' THEN 1 ELSE 0 END +
            CASE WHEN UPPER(COMMUNICATIONS_TELEPHONE) = 'YES' THEN 1 ELSE 0 END +
            CASE WHEN UPPER(COMMUNICATIONS_AIRPORT)   = 'YES' THEN 1 ELSE 0 END +
            CASE WHEN UPPER(COMMUNICATIONS_TELEFAX)   = 'YES' THEN 1 ELSE 0 END
        ) = 3 THEN 'Good'
        WHEN (
            CASE WHEN UPPER(COMMUNICATIONS_RADIO)     = 'YES' THEN 1 ELSE 0 END +
            CASE WHEN UPPER(COMMUNICATIONS_TELEPHONE) = 'YES' THEN 1 ELSE 0 END +
            CASE WHEN UPPER(COMMUNICATIONS_AIRPORT)   = 'YES' THEN 1 ELSE 0 END +
            CASE WHEN UPPER(COMMUNICATIONS_TELEFAX)   = 'YES' THEN 1 ELSE 0 END
        ) >= 1 THEN 'Limited'
        ELSE 'Unavailable'
    END AS COMMUNICATION_RATING,

    -- ── Derived: Port Depth Classification ───────────────────────────────────
    CASE
        WHEN GREATEST(COALESCE(CARGO_PIER_DEPTH_M, 0), COALESCE(CHANNEL_DEPTH_M, 0)) > 15  THEN 'Deep'
        WHEN GREATEST(COALESCE(CARGO_PIER_DEPTH_M, 0), COALESCE(CHANNEL_DEPTH_M, 0)) >= 8  THEN 'Medium'
        WHEN GREATEST(COALESCE(CARGO_PIER_DEPTH_M, 0), COALESCE(CHANNEL_DEPTH_M, 0)) > 0   THEN 'Shallow'
        ELSE 'Unknown'
    END AS PORT_DEPTH_CLASS

FROM {{ ref('silver_ports') }}
